name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Replace with your default branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Ensure this is the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Ensure this is the latest version
        with:
          node-version: '20'  # Use Node.js 20

      - name: Install dependencies
        run: npm ci  # Use `npm ci` for a cleaner install in CI environments

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
